debian/extra/lib/debian-ldap-query  usr/libexec/neomutt
debian/extra/lib/mailspell          usr/libexec/neomutt
debian/extra/lib/mailto-neomutt     usr/libexec/neomutt
debian/extra/lib/source-neomuttrc.d usr/libexec/neomutt
debian/extra/neomutt.desktop        usr/share/applications
debian/extra/rc/*.rc                etc/neomuttrc.d
debian/tmp/neomuttrc                etc
debian/tmp/usr/bin/neomutt
debian/tmp/usr/libexec/neomutt/*    usr/libexec/neomutt
debian/tmp/usr/share/icons/
debian/tmp/usr/share/locale/*
debian/tmp/usr/share/neomutt/logo/neomutt.svg usr/share/icons/hicolor/scalable/apps
usr/share/neomutt/account-command
usr/share/neomutt/colorschemes
usr/share/neomutt/mime.types
usr/share/neomutt/oauth2
usr/share/neomutt/smime.rc
usr/share/neomutt/vim-keys
